### ISSUE TITLE
[Table]: [For growing table, load more button is displayed even if the data is completely loaded in first time]

### ISSUE THREAD

**Issue by raoakash01** [UI5/webcomponents#11946]
### Describe the bug

When table is rendered "Load More" button is displayed in the bottom even if all the data is completely loaded at first time.

### Isolated Example

https://stackblitz.com/github/SAP/ui5-webcomponents-react/tree/main/templates/vite-ts?file=src%2FApp.tsx

### Reproduction steps

1.Navigate to https://stackblitz.com/github/SAP/ui5-webcomponents-react/tree/main/templates/vite-ts?file=src%2FApp.tsx

### Expected Behaviour

If there is no more data to load even after the first time "More" button should not be there

### Screenshots or Videos

<img width="1800" height="345" alt="Image" src="https://github.com/user-attachments/assets/cc28b631-2b1d-45df-8518-cdd9272bb3f2" />

### UI5 Web Components for React Version

2.7.1

### UI5 Web Components Version

2.7.0

### Browser

Chrome

### Relevant log output

```shell

```

### Declaration

- [x] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @raoakash01 

this behavior is by design. Please see the description of the [`TableGrowing` component](https://sap.github.io/ui5-webcomponents-react/v2/?path=/docs/data-display-table--docs#tablegrowing). 

> When the TableGrowing component is used with the Scroll mode and the table is currently not scrollable, the component will render a growing button instead to ensure growing capabilities until the table becomes scrollable.

You can find out more about it in this [comment](https://github.com/SAP/ui5-webcomponents/issues/10481#issuecomment-2620999216).

Btw, your example link only leads to our default template 😉 

___

Since this issue is essentially the same as the [one linked](https://github.com/SAP/ui5-webcomponents/issues/10481), I'm going to close this one. If you have any additional questions or feedback, please feel free to add them to the linked issue.

**Comment by raoakash01** [comment]
hey @Lukas742 
I pasted wrong example link initially 
correct example link

https://stackblitz.com/edit/github-gq3j47gb?file=src%2FApp.tsx

Issue 1 -> why do we get "More" button if there are only 2 items to load which are already loaded 
Issue 2-> If we render using condition why does the scroll does not work to load more data

<img width="1800" height="253" alt="Image" src="https://github.com/user-attachments/assets/e099d46d-2b67-4e72-84bf-9da9e5b54d06" />

<img width="1800" height="225" alt="Image" src="https://github.com/user-attachments/assets/7bce7296-0d35-437e-8e44-37f223ff0b0a" />

please re-open the ticket again

**Comment by Lukas742** [comment]
Hi @raoakash01 

> Issue 1 -> why do we get "More" button if there are only 2 items to load which are already loaded

Please see the comment I linked previously:  https://github.com/SAP/ui5-webcomponents/issues/10481#issuecomment-2620999216
So, if there's no more data to load, remove the growing feature. 

> Issue 2-> If we render using condition why does the scroll does not work to load more data

This looks like a bug to me. As the `Table` and all of its subcomponents are developed in the ui5-webcomponents repo, I'll transfer this issue there.

___

Hi Colleagues,

the "Scroll" grow feature doesn't seem to work when a `height` is applied to the table itself. When applied to the surrounding container, it's working as intended - but this makes it impossible to implement a sticky header.

This behavior can also be observed in your playground example: https://sap.github.io/ui5-webcomponents/components/TableGrowing/#growing-with-scrolling

**Comment by raoakash01** [comment]
hey @Lukas742 

I have put table inside a div and give to height but still. I observed uncertain behaviour like neither getting "More" Button nor the scroll

**Comment by Lukas742** [comment]
Hi @raoakash01 
From what I understand, there should be a "More" button displayed, given that the table isn't scrollable. So to me, this does appear to be a bug.

Colleagues, could you please check this as well?

**Comment by NHristov-sap** [comment]
Hello @SAP/ui5-webcomponents-table ,

Please take a look on this issue.

Best Regards,
Nikolay Hristov

**Comment by raoakash01** [comment]
hey @Lukas742 @NHristov-sap 

I have noticed one more bug in Table component adding example below.->
https://stackblitz.com/edit/github-x1qu3jyu?file=src%2FApp.tsx

table works fine with scroll when screen is on 100% but once we zoom it to 80% scroll does not work.
we can zoom more and we get load more button we can use it it will load more data for once but then again it stops working.

Browser -> Chrome

**Comment by maltenorstroem** [comment]
> hey [@Lukas742](https://github.com/Lukas742) [@NHristov-sap](https://github.com/NHristov-sap)
> 
> I have noticed one more bug in Table component adding example below.-> https://stackblitz.com/edit/github-x1qu3jyu?file=src%2FApp.tsx
> 
> table works fine with scroll when screen is on 100% but once we zoom it to 80% scroll does not work. we can zoom more and we get load more button we can use it it will load more data for once but then again it stops working.
> 
> Browser -> Chrome

We have observed the same behavior.

**Comment by raoakash01** [comment]
Hi @Lukas742 @NHristov-sap 
What's the update regarding this ticket ?

**Comment by aborjinik** [comment]
Hi @raoakash01 this problem occurs because the growing button increases the height of the scrolling area, creating the impression that the table is actually scrollable. As a result, the table expects the events to come from the scroll event instead. However when the growing button is hidden, the table is no longer scrollable, so of course no scroll events are fired anymore. You can test this by increasing or decreasing the initially rendered row count in your example, or by adjusting the height of the overflow area.

The good news is that for accessibility reasons, the growing button is no longer inside the scrollable area https://github.com/UI5/webcomponents/pull/12468, which means this issue should be resolved in the new version. Could you please test again with the nightly version?

PS: Unfortunately, the example that @Lukas742 mentioned in the playground still uses the old `type=Scroll` property instead of the new `mode` property. I will fix that.

**Comment by raoakash01** [comment]
Hey @aborjinik @Lukas742 
Thanks for all the updates but I still see one issue here

https://stackblitz.com/edit/github-x1qu3jyu?file=src%2FApp.tsx

in this example we have used mode={hasMoreRecords ? 'Scroll' : undefined}
even if we have no more data to load we get more button with the table

I have also tried with mode={'Scroll'} and saw the same behaviour.

**Comment by aborjinik** [comment]
@raoakash01 There is no data-store concept in the Web Components table, meaning the table itself has no knowledge of whether more rows are available to load. Changing the mode simply changes the mode, setting it to undefined makes the table fall back to its default value, which is Button.
If there is no more data to load, as in your previous example (table2), you should remove the growing feature from the table.
